url = "https://abcdlsj.github.io"
pub_url = "https://blog.songjian.li"
title = "abcdlsj's blog"
description = "Enjoy Focus!"
author = "abcdlsj"
keywords = ["blog", "programming", "technology", "life", "travel", "reading", "movies", "games", "animals", "hardware", "software", "ai", "career", "personal"]

[[menus]]
slug = "home"
name = "Home"
url = ""

[[menus]]
slug = "posts"
name = "Posts"
url = "posts"
dir = true

[[menus]]
slug = "about"
name = "About"
url = "about"
dir = true

[[menus]]
slug = "hosts"
name = "Hosts"
url = "hosts"
hide = true
dir = true

[[menus]]
slug = "rss"
name = "Feed"
url = "rss.xml"

[build]
posts = "abcdlsj.github.io/posts"
output = "abcdlsj.github.io/public"
static = "abcdlsj.github.io/static"

[[host]]
name = "DDIA"
source = "abcdlsj.github.io/submodules/ddia"
output = "hosts/ddia"
type = "static"
